import { IEmployee } from "../interfaces/employee";

export const demoEmployees: IEmployee[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    phone: "123-456-7890",
    gender: "Male",
    department: "Engineering",
    role: "Developer",
    isActive: true,
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "234-567-8901",
    gender: "Female",
    department: "Marketing",
    role: "Manager",
    isActive: true,
  },
  {
    id: "3",
    name: "Alice Johnson",
    email: "alice@example.com",
    phone: "345-678-9012",
    gender: "Female",
    department: "HR",
    role: "Recruiter",
    isActive: false,
  },
  {
    id: "4",
    name: "Bob Brown",
    email: "bob@example.com",
    phone: "456-789-0123",
    gender: "Male",
    department: "Finance",
    role: "Analyst",
    isActive: true,
  },
  {
    id: "5",
    name: "Charlie Davis",
    email: "charlie@example.com",
    phone: "567-890-1234",
    gender: "Male",
    department: "Support",
    role: "Technician",
    isActive: false,
  },
];
